language: python
python:
- '3.6'
branches:
  only:
  - master
env:
- DJANGO=2.0
install:
- touch aa.txt
script:
- touch bb.txt
before_install:
- openssl aes-256-cbc -K $encrypted_b9b8a2ac834f_key -iv $encrypted_b9b8a2ac834f_iv
  -in django.enc -out django -d
- openssl aes-256-cbc -K $encrypted_2bc13221a680_key -iv $encrypted_2bc13221a680_iv
  -in id_rsa_deploy.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: ${HOST}:${PORT}
after_success:
- ssh -p ${PORT} -tt ${USER}@${HOST} < run.sh
