language: python
python:
  - '3.6'
branches:
  only:
  - master
env:
  - DJANGO=2.0
install:
  - touch aa.txt
script:
  - touch bb.txt
before_install:
  - openssl aes-256-cbc -K $encrypted_b9b8a2ac834f_key -iv $encrypted_b9b8a2ac834f_iv -in django.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: ${HOST}:${PORT}
after_success:
  - ssh -o StrictHostKeyChecking=no -p ${PORT} ${USER}@${HOST} < run.sh
