language: python
python:
- '3.6'
branches:
    only:
    - master
env:
- DJANGO=2.0
install:
- cd proj/
- pip install -r requirements.txt
script:
- python manage.py test users.tests.UserTestCase

before_install:
- openssl aes-256-cbc -K $encrypted_2bc13221a680_key -iv $encrypted_2bc13221a680_iv
  -in id_rsa_deploy.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
  # - cp .travis/ssh_config ~/.ssh/config
addons:
    ssh_known_hosts: 123.123.123.123
after_success:
- ssh -tt ubuntu@123.123.123.123 < run.sh